---
title: "Ocean Uses and Marine Renewable Energy"
author: "Ben Best"
date: '`r format(Sys.time(), "%Y-%m-%d %H:%M")`'
output:
  html_document:
    toc: yes
    toc_depth: '4'
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    toc: yes
  word_document:
    toc: yes
    toc_depth: '4'
---

```{r setup, include=FALSE}
# TODO: 
# - + tide, wave
# - table of layer x territory: present/absent.
knitr::opts_chunk$set(warning=F, message=F, eval=T, echo=F, cache=F)

source(here::here("scripts/setup.R"))
devtools::load_all(here("../nrelutils"))

i_tbl <<- 0
src <- NULL

# iterate over territories and bins
territories <- eez_s05_wgcs_sf$territory
# territories <- c("Alaska", "Atlantic Islands", "East", "Great Lakes", "Gulf of Mexico", "Hawaii", "Pacific Islands", "West")
#territories <- c("Alaska", "East", "Great Lakes")
# bins <- names(limits) # 
bins <- c("depth","wind","wave")
# territories <- c("Atlantic Islands", "East"); bins <- c("depth")

for (ter in territories){ # ter = territories[1] # "Alaska" # "Atlantic Islands" # territories[1]
  msg(g("{ter}"))
  
  src <- c(src, glue("
## {ter}

```{{r {ter}}}
ter <- '{ter}'
```"))
  
  # devtools::load_all("~/github/nrelutils") 
  ter_info  <- make_ter_info(ter, lyr_params, bins)
  
  src <- c(src, glue("
### {ter}: Map of Uses

```{{r map{ter}, fig.cap=\"{map_ter_caption(ter, 'all', 'count')}\"}}
map_ter(ter, 'all', 'count')
```"))
  
  for (bin in bins){ # bin = bins[1]
    
    if (is.na(ter_info[[bin]][1])) next
    
    bin_cap  <- stringr::str_to_title(bin)
    bin_html    <- lyr_params %>% 
      filter(key == bin) %>%
      .$title
    
    src <- c(src, glue("
```{{r {ter}-{bin}}}
bin         <- '{bin}'
bin_cap     <- '{bin_cap}'
bin_html    <- '{bin_html}'
```"))

    src <- c(src, glue("
### {ter}: Map of {bin_cap}

```{{r map{ter}{bin}, fig.cap=\"{map_ter_caption(ter, bin, 'limits')}\"}}
map_ter(ter, bin, 'limits')
```"))

    src <- c(src, glue("
### {ter}: Plot of Uses by {bin_cap}

```{{r fig{ter}{bin}, fig.cap='{plot_caption_ter_bin_cnt(ter, bin_html)}'}}
plot_ter_bin_cnt(ter, bin)
```"))
    
    src <- c(src, glue("
### {ter}: Table of Uses by {bin_cap}

```{{r tbl{ter}{bin}}}
tbl_blsp <- ter_bin_lyr_smry_plus(ter, bin, lyr_params, lyr_categories)
print_ter_bin_lyr_smry_plus(tbl_blsp)
```"))

  }
}

src <- glue("{src}\n")
write_lines(src, here("docs/nrel-uses_src.Rmd"))
res = knit_child(text = unlist(src))
```

```{r knitted_result, results="asis", eval=T}
cat(paste(res, collapse = "\n"))
```
